#!/bin/bash
now=$(date +"%Y%m%d_%H%M")
# Delete Old Extra Modules
rm ~/android/AnyExtra/system/lib/modules/tun.ko
rm ~/android/AnyExtra/system/lib/modules/librasdioif.ko
# Add New Extra Modules
cp ~/android/caf-kernel/drivers/net/tun.ko ~/android/AnyExtra/system/lib/modules/tun.ko
cp ~/android/caf-kernel/drivers/net/wireless/libra/librasdioif.ko ~/android/AnyExtra/system/lib/modules/librasdioif.ko
# Creat flashable zip file
cd ~/android/AnyExtra
zip -r extra-${now}.zip *
# Drop it to release folder
mv ~/android/AnyExtra/extra-${now}.zip ~/android/releasefolder
